/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#898281',
        'primary-fixed-dim': '#c8c6c8',
        'on-secondary-fixed': '#161a32',
        'tertiary-fixed': '#eae0de',
        'on-primary-fixed': '#1b1b1d',
        'on-secondary': '#ffffff',
        background: '#f8f9fa',
        'on-primary-container': '#858386',
        'surface-container-low': '#f3f4f5',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'secondary-fixed': '#dee0ff',
        'primary-fixed': '#e4e2e4',
        'on-surface-variant': '#46464a',
        'on-surface': '#191c1d',
        'secondary-container': '#dbdeff',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#414560',
        'on-tertiary': '#ffffff',
        'surface-tint': '#5f5e60',
        'on-primary-fixed-variant': '#474649',
        'inverse-primary': '#c8c6c8',
        'tertiary-container': '#1f1b1a',
        'on-secondary-container': '#5d617d',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#1f1b1a',
        'outline-variant': '#c7c6ca',
        'surface-container-highest': '#e1e3e4',
        surface: '#f8f9fa',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#4b4644',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-dim': '#d9dadb',
        secondary: '#595d78',
        'surface-container-high': '#e7e8e9',
        'tertiary-fixed-dim': '#cdc5c3',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
        'surface-container': '#edeeef',
        'primary-container': '#1b1b1d',
        primary: '#000000',
        outline: '#77767b',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#c1c4e5',
        'surface-bright': '#f8f9fa',
        tertiary: '#000000',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        md: '1.5rem',
        xl: '4rem',
        unit: '4px',
        'max-width': '1200px',
        gutter: '1.5rem',
        sm: '1rem',
        'margin-desktop': '5rem',
        lg: '2.5rem',
        xs: '0.5rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Hanken Grotesk'],
        'label-sm': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'display-lg': ['Hanken Grotesk'],
        'title-md': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        'body-md': ['Hanken Grotesk'],
        'label-md': ['Hanken Grotesk'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};